import { mrnScanerService } from './mrn-scaner';
import { updateDoctorService,
         updateDoctorPhotoService,
         getDoctorService,
         getDoctorKeyListService,
         getDoctorByEmailService } from './doctor';
import { getPatientMolesService,
         addMoleService,
         getMoleService,
         updateMoleService,
       } from './mole';
import { addMolePhotoService,
         getMolePhotoService,
         updateMolePhotoService,
       } from './photo';
import { addAnatomicalSitePhotoService, getAnatomicalSitesService } from './anatomical-site.js';
import { patientsService,
         getPatientService,
         createPatientService,
         updatePatientService,
         updatePatientConsentService,
       } from './patients';
import { getSiteJoinRequestsService,
         createSiteJoinRequestService,
         confirmSiteJoinRequestService,
       } from './site-join-requests';
import { getStudiesService,
         addStudyConsentService,
       } from './study';
import { getInvitesService,
         approveInviteService,
         declineInviteService,
         sendInviteToDoctorService,
         approveInviteForDoctorService,
         declineInviteForDoctorService,
         getPatientsWaitingForDoctorApproveService,
       } from './invites';


export default {
    mrnScanerService,
    updateDoctorService,
    updateDoctorPhotoService,
    getDoctorService,
    getDoctorKeyListService,
    getDoctorByEmailService,
    getPatientMolesService,
    addMoleService,
    getMoleService,
    updateMoleService,
    addMolePhotoService,
    getMolePhotoService,
    updateMolePhotoService,
    addAnatomicalSitePhotoService,
    getAnatomicalSitesService,
    patientsService,
    getPatientService,
    createPatientService,
    updatePatientService,
    updatePatientConsentService,
    getPatientsWaitingForDoctorApproveService,
    getSiteJoinRequestsService,
    createSiteJoinRequestService,
    confirmSiteJoinRequestService,
    getStudiesService,
    addStudyConsentService,
    getInvitesService,
    approveInviteService,
    declineInviteService,
    sendInviteToDoctorService,
    approveInviteForDoctorService,
    declineInviteForDoctorService,
};
