import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    face: {
        top: 0,
        left: 129,
        width: 61,
        height: 68,
    },
    anteriorNeck: {
        top: 69,
        left: 141,
        width: 37,
        height: 18,
    },
    leftUpperChest: {
        top: 110,
        right: 108,
        width: 51,
        height: 88,
    },
    rightUpperChest: {
        top: 111,
        left: 107,
        width: 52,
        height: 87,
    },
    middleChest: {
        top: 88,
        left: 141,
        width: 38,
        height: 80,
    },
    leftUpperAbdomen: {
        top: 199,
        right: 107,
        width: 52,
        height: 60,
    },
    rightUpperAbdomen: {
        top: 199,
        left: 107,
        width: 52,
        height: 60,
    },
    leftLowerAbdomen: {
        top: 261,
        right: 95,
        width: 64,
        height: 75,
    },
    rightLowerAbdomen: {
        top: 261,
        left: 95,
        width: 64,
        height: 75,
    },

    leftAnteriorShoulder: {
        top: 91,
        right: 77,
        width: 66,
        height: 68,
    },
    rightAnteriorShoulder: {
        top: 90,
        left: 76,
        width: 67,
        height: 68,
    },
    leftAnteriorUpperArm: {
        top: 148,
        right: 67,
        width: 42,
        height: 48,
    },
    rightAnteriorUpperArm: {
        top: 147,
        left: 66,
        width: 42,
        height: 47,
    },
    leftAntecubitalFossa: {
        top: 183,
        right: 52,
        width: 44,
        height: 46,
    },
    rightAntecubitalFossa: {
        top: 183,
        left: 52,
        width: 44,
        height: 46,
    },
    leftAnteriorForearm: {
        top: 218,
        right: 32,
        width: 51,
        height: 77,
    },
    rightAnteriorForearm: {
        top: 218,
        left: 32,
        width: 50,
        height: 77,
    },
    leftPalm: {
        top: 289,
        right: 0,
        width: 54,
        height: 69,
    },
    rightPalm: {
        top: 289,
        left: 0,
        width: 53,
        height: 69,
    },

    leftAnteriorThigh: {
        top: 316,
        right: 93,
        width: 66,
        height: 77,
    },
    rightAnteriorThigh: {
        top: 316,
        left: 92,
        width: 66,
        height: 77,
    },
    leftKnee: {
        top: 394,
        right: 98,
        width: 51,
        height: 69,
    },
    rightKnee: {
        top: 394,
        left: 98,
        width: 51,
        height: 69,
    },
    leftProximalLowerLeg: {
        top: 464,
        right: 100,
        width: 42,
        height: 47,
    },
    rightProximalLowerLeg: {
        top: 464,
        left: 99,
        width: 43,
        height: 48,
    },
    leftDistalLowerLeg: {
        top: 513,
        right: 104,
        width: 37,
        height: 44,
    },
    rightDistalLowerLeg: {
        top: 513,
        left: 103,
        width: 38,
        height: 44,
    },
    leftDorsalFoot: {
        top: 558,
        right: 99,
        width: 39,
        height: 65,
    },
    rightDorsalFoot: {
        top: 558,
        left: 99,
        width: 38,
        height: 65,
    },
});
