# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Skin' do
  use_frameworks!
  pod 'SnapKit'
end

target 'BodyView3D-Test' do
  use_frameworks!
  pod 'SnapKit'
end
