import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    face: {
        top: 0,
        left: 130,
        width: 58,
        height: 63,
    },
    middleChest: {},
    anteriorNeck: {},
    leftUpperChest: {},
    rightUpperChest: {},
    leftUpperAbdomen: {},
    rightUpperAbdomen: {},
    leftLowerAbdomen: {},
    rightLowerAbdomen: {},

    leftAnteriorShoulder: {},
    rightAnteriorShoulder: {},
    leftAnteriorUpperArm: {},
    rightAnteriorUpperArm: {},
    leftAntecubitalFossa: {},
    rightAntecubitalFossa: {},
    leftAnteriorForearm: {},
    rightAnteriorForearm: {},
    leftPalm: {},
    rightPalm: {},

    leftAnteriorThigh: {},
    rightAnteriorThigh: {},
    leftKnee: {},
    rightKnee: {},
    leftProximalLowerLeg: {},
    rightProximalLowerLeg: {},
    leftDistalLowerLeg: {},
    rightDistalLowerLeg: {},
    leftDorsalFoot: {},
    rightDorsalFoot: {},
});
