import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    head: {
        left: 131,
        width: 68,
        height: 76,
        justifyContent: 'flex-end',
    },
    neck: {
        left: 141,
        top: 76,
        width: 38,
        height: 91,
    },
    rightShoulder: {
        left: 81,
        top: 92,
        height: 66,
        width: 64,
    },
    rightChest: {
        right: 160,
        top: 111,
        height: 82,
        width: 50,
    },
    leftShoulder: {
        right: 81,
        top: 92,
        height: 66,
        width: 64,
    },
    leftChest: {
        left: 160,
        top: 111,
        height: 82,
        width: 50,
    },
    upperRightPelvis: {
        right: 160,
        top: 193,
        height: 58,
        width: 50,
    },
    upperLeftPelvis: {
        left: 158,
        top: 193,
        height: 58,
        width: 50,
    },
    lowerRightPelvis: {
        right: 160,
        top: 251,
        height: 72,
        width: 61,
    },
    lowerLeftPelvis: {
        left: 158,
        top: 251,
        height: 72,
        width: 61,
    },
    rightElbow: {
        left: 63,
        top: 145,
        height: 66,
        width: 50,
    },
    leftElbow: {
        right: 63,
        top: 145,
        height: 66,
        width: 50,
    },
    rightForearm: {
        left: 51,
        top: 198,
        height: 50,
        width: 45,
    },
    leftForearm: {
        right: 50,
        top: 198,
        height: 50,
        width: 45,
    },
    rightWrist: {
        left: 39,
        top: 238,
        height: 50,
        width: 42,
    },
    leftWrist: {
        right: 37,
        top: 237,
        height: 50,
        width: 42,
    },
    rightHand: {
        left: 10,
        top: 277,
        height: 79,
        width: 56,
    },
    leftHand: {
        right: 7,
        top: 277,
        height: 79,
        width: 56,
    },
    rightThigh: {
        left: 96,
        top: 302,
        height: 75,
        width: 65,
    },
    leftThigh: {
        right: 95,
        top: 302,
        height: 75,
        width: 65,
    },
    rightKnee: {
        left: 101,
        top: 375,
        height: 66,
        width: 60,
    },
    leftKnee: {
        right: 92,
        top: 375,
        height: 66,
        width: 60,
    },
    rightShin: {
        left: 102,
        top: 441.5,
        height: 45,
        width: 60,
    },
    leftShin: {
        right: 86,
        top: 441.5,
        height: 45,
        width: 60,
    },
    rightAnkle: {
        left: 106,
        top: 485,
        height: 42,
        width: 60,
    },
    leftAnkle: {
        right: 85,
        top: 485,
        height: 42,
        width: 60,
    },
    rightFoot: {
        left: 102,
        top: 527,
        height: 42,
        width: 60,
    },
    leftFoot: {
        right: 82,
        top: 529,
        height: 42,
        width: 60,
    },
});
