import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    head: {
        top: 0,
        left: 131,
        width: 70,
        height: 75,
        justifyContent: 'flex-end',
    },
    neck: {
        top: 76,
        left: 142,
        width: 36,
        height: 89,
    },
    rightChest: {
        top: 113,
        right: 161,
        width: 49,
        height: 80,
    },
    leftChest: {
        top: 113,
        left: 160,
        width: 49,
        height: 80,
    },
    upperRightPelvis: {
        top: 194,
        right: 161,
        width: 49,
        height: 56,
    },
    upperLeftPelvis: {
        top: 195,
        left: 160,
        width: 50,
        height: 56,
    },
    lowerRightPelvis: {
        top: 252,
        right: 162,
        width: 60,
        height: 70,
    },
    lowerLeftPelvis: {
        top: 252,
        left: 160,
        width: 61,
        height: 70,
    },
    rightShoulder: {
        top: 93,
        left: 81,
        width: 74,
        height: 67,
    },
    leftShoulder: {
        top: 93,
        right: 71,
        width: 73,
        height: 66,
    },
    rightElbow: {
        top: 146,
        left: 63,
        width: 50,
        height: 64,
    },
    leftElbow: {
        top: 146,
        right: 63,
        width: 51,
        height: 65,
    },
    rightForearm: {
        top: 200,
        left: 51,
        width: 46,
        height: 49,
    },
    leftForearm: {
        top: 200,
        right: 50,
        width: 45,
        height: 49,
    },
    rightWrist: {
        top: 238,
        left: 40,
        width: 46,
        height: 50,
    },
    leftWrist: {
        top: 238,
        right: 32,
        width: 46,
        height: 50,
    },
    rightHand: {
        top: 278,
        left: 10,
        width: 59,
        height: 79,
    },
    leftHand: {
        top: 278,
        right: 5,
        width: 58,
        height: 78,
    },
    rightThigh: {
        top: 303,
        left: 96,
        width: 66,
        height: 73,
    },
    leftThigh: {
        top: 303,
        right: 94,
        width: 66,
        height: 74,
    },
    rightKnee: {
        top: 377,
        left: 101,
        width: 60,
        height: 64,
    },
    leftKnee: {
        top: 377,
        right: 92,
        width: 60,
        height: 64,
    },
    rightShin: {
        top: 442,
        left: 102,
        width: 59,
        height: 44,
    },
    leftShin: {
        top: 442,
        right: 86,
        width: 60,
        height: 44,
    },
    rightAnkle: {
        top: 487,
        left: 106,
        width: 60,
        height: 40,
    },
    leftAnkle: {
        top: 487,
        right: 83,
        width: 61,
        height: 41,
    },
    rightFoot: {
        top: 529,
        left: 102,
        width: 73,
        height: 63,
    },
    leftFoot: {
        top: 529,
        right: 69,
        width: 73,
        height: 64,
    },
});
